/* *****
** upper: newer news
** lower: older one
** BE CAREFUL TO USE "TAGS" !!! DONT FORGET ESCAPES(\), etc !!!
** 0 : news    1 : update    2 : conference
***** */
var NEWS_TITLE =
[
["2016/3/12","0","岡田明帆さんが，能動的なロボットと人の関係についての考察，にて情報処理学会第78回全国大会にて，学生奨励賞を受賞しました！"],
["2016/3/12","0","岡崎純己君が，リハビリテーション促進ロボットの実現に向け，にて情報処理学会第78回全国大会にて，学生奨励賞を受賞しました！"],
["2016/2/10","0","住谷拓馬君(M2)が今年度の大学院（電気電子情報工学専攻）の業績の秀でた学生に贈られる専攻賞に選ばれました."],
["2016/1/28","0","情報処理学会　第78回全国大会にて発表します."],
["2016/1/28","0","中山悟君さんが<br/>SEATUC 2016　10th SOUTH EAST ASIAN TECHNICAL UNIVERSITY CONSORTIUM SYMPOSIUM、<br/>DEIM2016　第8回データ工学と\
情報マネジメントに関するフォーラム（第14回日本データベース学会年次大会）<br/>にて発表します."],
["2016/1/28","0","住谷拓馬君、小野建也君がETNET2016にて発表します."],
["2016/1/28","0","西田祐己君、西村拓哉君、岡田明帆さんがインタラクション2016にてポスター発表します."],
["2015/12/23","0","3年生の新配属メンバーが決定しました!"],
["2015/12/23","0","Human Computer Interaction International (HCII 2016, Canada, Toronto), に岡田明帆，池田悠平，保科篤志の論文，３本が採択されました"],
["2015/12/15","0","ロボット向け情報技術・設計技術に関する情報交換会を開催します"],["2015/12/15","0","中山悟君，柳田将希君がSETUC2016 に採択されました. "],["2015/12/01","0","2015/12, 青山学院大学で，３研究室合同研究発表会を実施します（青山学院大学/戸辺研究室, 法政大/藤田研究室）"],
["2015/12/01","2","2015/12, 国際ロボット展の展示(デモブース）に参加します．"],
["2015/10/13","0","2015/10/13,20 5限，503教室にてプレゼミを実施しました．"],
["2015/09/11","0","2015/09,HAI 2015: The 3rd International Conference on Human-Agent Interaction Proceedings 2015 に採択されました．"],
["2015/09/10","0","2015/09,人間情報学会にて，岡田明帆(B4) が Poster 発表しました．"],
["2015/09/07","2","2015/09，KES (19th International Conference on Knowledge-Based and Intelligent Information & Engineering Systems at Singapore) 2015にて，住谷拓馬君(M2) が発表します"],
["2015/09/07 0:00:00","2","UbiComp 2015 Workshop (Smart Cities' 2015) にて，保科篤志君（B4) が Poster 発表します．"],
["2015/09/05","0","2015/09,大倉研, 木村研とプレ中間を実施しました．"],
["2015/08/31","0","2015/08,Exciting Coding 2015 (情報処理学会主催）の企画に，運営委員として柳田将希君(M1) が参加します．"],
["2015/08/31","0","2015/08,研究室Summer Internship を実施しました．"],
["2015/08/31 0:00:00","2","2015/08,RO-MAN (The 24th International Symposium on Robot and Human Interactive Communication 2015)Workshop (Toy Robots/ Digital environments and Cognitive Developmental Neuroscience) にて，菅谷が発表をします"],
["2015/08/30 0:00:00","2","2015/08,研究室合宿で熱海に行ってきます！"],
["2015/08/07 0:00:00","2","2015/08,HCII (Human Computer Interaction International 2015, at Los Angeles) にて菅谷が発表します"],
["2015/07/30","0","2015/07,東京農工大で合同研究発表会を実施しました（東京農工大/藤波研)"],
["2015/07/09 0:00:00", "2", "DICOMO2015シンポジウムで住谷拓馬君と池田悠平君が発表を行います."],
["2015/06/29 0:00:00","2","CNR (クラウドネットワークロボット研究会）にて，柳田将希(M1)が発表します."],
["2015/06/11 0:00:00", "1", "2015年豊洲Dayにて,研究室紹介とデモ発表を行いました！"],
["2015/06/09 0:00:00", "0", "豊洲Dayにて研究室紹介，デモを行います！"],
["2015/05/09 0:00:00", "2", "enPITスプリングスクールに参加してきました．"],
["2015/05/01 0:00:00", "2", "CHI 2015にて，菅谷 みどり准教授が発表を行います."],
["2015/05/01 0:00:00", "2", "UBI第46回研究会にて，渡辺 柚佳子さんの表彰式,菅谷 みどり准教授が吉田 裕幸君の研究発表を行います."],
["2015/05/01 0:00:00", "2", "第20回人間情報学会にて，池田君，保科君がポスタ発表を行いました."],
	["2015/05/01 0:00:00", "2","優秀教育教員顕彰制度にて，プログラム入門1が受賞しました."],
	["2015/01/16 0:00:00", "2", "第45回ユビキタス研究会（芝浦，豊洲キャンパス）にて，渡辺柚佳子さんが発表します."],
	["2015/01/16 0:00:00", "2", "組込み技術とネットワークに関するワークショップ ETNET2015 にて，中山悟君が発表します．"],
//	["2015/01/16 0:00:00", "2", "HCI インタラクション2015に樫村健人君のポスターが採択されました"],
	["2015/01/16 0:00:00", "2", "第77回，情報処理学会全国大会にて，柳田将希君，東拓磨君，宮入崇誠君，（中山悟君），長峰貴矩君（住谷拓馬君）が発表します．"],
	["2015/01/16 0:00:00", "1", "3年生の新配属メンバーが決定しました！"],
	["2014/12/19 0:00:00", "2", "HCI International Conference 2015 に採択されました．"],
	["2014/11/06 0:00:00", "2", "HAI2014にて， 渡辺さん，樫村君のポスター発表がBEST POSTER AWARD First Place を受賞しました！"],
	["2014/11/06 0:00:00", "2", "第43回UBI研究発表会にて，渡辺 柚佳子さんの発表が学生奨励賞を受賞しました！"],
	["2014/10/21 0:00:00", "0", "[10/29&nbsp;追記]プレゼミについて。レポート提出期限を変更しました！"],
	["2014/10/10 0:00:00", "0", "[10/10 15:54修正]中間発表します"],
	["2014/10/01 0:00:00", "2", "Summer Workshop on Embedded System Technologies 16"],
	["2014/10/01 0:00:00", "0", "FabGirl Workhop 開催! (9/25-27) "],
	["2014/10/01 0:00:00", "2", "エンターテイメントコンピューティング 2014, (9/12-14)"],
	["2014/10/01 0:00:00", "2", "2nd International Conference on Human-Agent Interaction (HAI 2014) Oct 28-31"],
	["2014/07/27 0:00:00", "0", "オープンキャンパス（大宮,&nbsp;8/3）でロボット,&nbsp;デバイスを出展します。"],
	["2014/07/27 0:00:00", "0", "ロボット実習（1年生,&nbsp;3年生）を行いました。"],
	["2014/07/27 0:00:00", "2", "ユビキタス研究会で渡辺さんが発表します(7/28)。"],
	["2014/07/27 0:00:00", "2", "SWEST で住谷君，長峰君，近藤君がポスター発表（8/29) します。"],
	["2014/07/27 0:00:00", "0", "FabGirl ワークショップ開催します（7/25&nbsp;-&nbsp;7/27)。"],
	["2014/07/16 0:00:00", "1", "FabGirl Projectページがリニューアルしました。"],
	["2014/06/18 0:00:00", "1", "豊洲Dayでの紹介ページを公開しました。"],
	["2014/06/08 0:00:00", "0", "6/10(火) 豊洲Dayで各研究デモを披露しました。"],
	["2014/05/20 0:00:00", "2", "情報処理学会 第184回SE・第33回EMB合同研究発表会で発表しました。"],
	["2014/01/01 0:00:00", "2", "第157回, ヒューマンコンピュータインタラクション研究会で発表しました."],
	["2014/01/01 0:00:00", "2", "情報処理学会会全国大会で発表しました．住谷君が学生奨励賞を受賞しました!"],
	["2014/01/01 0:00:00", "2", "インタラクション 2014 のインタラクティブ発表に参加しました．"],
	["2014/01/01 0:00:00", "2", "コンピュータシステムシンポジウムで発表しました．"],
	["2014/01/01 0:00:00", "2", "組込みシステムシンポジウムで発表しました．"]
];

var NEWS_DETAIL =

[
"簡易プログラム：<a href=\"https://www.gakkai-web.net/gakkai/ipsj/78/program78.html\">https://www.gakkai-web.net/gakkai/ipsj/78/program78.html</a><br/>詳細：<a href=\"http://www.gakkai-web.net/gakkai/ipsj/78program/data/pdf/4G-02.html\">http://www.gakkai-web.net/gakkai/ipsj/78program/data/pdf/4G-02.html</a><br/>岡田明帆，菅谷みどり，能動的なロボットと人の関係についての考察，情報処理学会，第78回全国大会，2016, 3.",
"簡易プログラム：<a href=\"https://www.gakkai-web.net/gakkai/ipsj/78/program78.html\">https://www.gakkai-web.net/gakkai/ipsj/78/program78.html</a><br/>詳細：<a href=\"http://www.gakkai-web.net/gakkai/ipsj/78program/data/pdf/6ZB-02.html\">http://www.gakkai-web.net/gakkai/ipsj/78program/data/pdf/6ZB-02.html</a><br/>岡岡崎純己，松日楽信人，菅谷みどり, リハビリテーション促進ロボットの実現に向け情報処理学会第78回全国大会，2016, 3.",
"リンクを貼る予定です",
"情報処理学会　第78回全国大会<br/>日時：平成28年3月10日～12日<br/>会場：慶應義塾大学　矢上キャンパス<br/>リンク：<a href=\"http://www.ipsj.or.jp/event/taikai/78/\">http://www.ipsj.or.jp/event/taikai/78/</a><br/>タイトル：復数台の分散移動ロボットの動作と電力消費特性に基づく管理手法の提案<br/>　　清水航平、中山悟、菅谷みどり,<br/>タイトル：コンテキストプログラミングのロボット事例への適用検討<br/>　　小野建也、菅谷みどり<br/>タイトル：能動的なロボットと人の関係についての考察<br/>　　岡田明帆、菅谷みどり<br/>タイトル：分散ロボットシステムサーバのための応答性向上手法<br/>　　中山悟、中野美由紀、菅谷みどり<br/>タイトル：Haptic Vertual：視覚および触覚が生体情報に及ぼす影響<br/>　　保科篤志、岡田佳子、菅谷みどり<br/>タイトル：リハビリテーション促進ロボットの実現に向け<br/>　　岡崎純己、松日楽信人、菅谷みどり<br/>タイトル：Project_Based Learningにおける役割を元にした分析および効果測定<br/>　　木谷健太、谷田川ルミ、菅谷みどり",
"SEATUC 2016　10th SOUTH EAST ASIAN TECHNICAL UNIVERSITY CONSORTIUM SYMPOSIUM<br/>日時：平成28年2月22日～24日<br/>会場：芝浦工業大学<br/>タイトル：<br/>リンク：<a href=\"http://www.utm.my/international/seatuc-2016/\">http://www.utm.my/international/seatuc-2016/</a><br/><br/>DEIM2016　第8回データ工学と情報マネジメントに関するフォーラム（第14回日本データベース学会年次大会）<br/>日時：平成28年2月29日～3月2日<br/>会場：ヒルトン福岡シーホーク<br/>リンク：<a href=\"http://db-event.jpn.org/deim2016/\">http://db-event.jpn.org/deim2016/</a><br/><br/>タイトル：分散ロボットシステムサーバのための応答性向上手法に関する考察<br/>　　中山悟、中野美由紀、菅谷みどり<br/>",
"ETNET2016<br/>日時：平成28年3月24日、25日<br/>会場：福江文化会舘（2F会議室）及び勤労福祉センター（2F第一講習室）<br/>タイトル：IXM：ロボット制御ソフトウェア向けプロセス間通信ミドルウエア<br/>　　住也拓馬、松原豊、菅谷みどり<br/>タイトル：コンテキスト指向プログラミング手法のロボット事例への適用検討<br/>　　小野建也、菅谷みどり<br/>リンク：<a href=\"http://sigarc.ipsj.or.jp/mtg/fy2015/arc211/\">http://sigarc.ipsj.or.jp/mtg/fy2015/arc211/</a>",
"インタラクション<br/>日時：平成28年3月2日～4日<br/>会場：科学技術館<br/>タイトル：幼児向けARとKinectによる言葉遊び支援システム<br/>　　西田裕己、西村拓哉、菅谷みどり<br/>タイトル：ロボットの能動的な行動設計によるユーザの印象評価の向上<br/>　　岡田明帆,菅谷みどり<br/>リンク:<a href=\"http://www.interaction-ipsj.org/2016/\">http://www.interaction-ipsj.org/2016/</a>",
"<DL>http://www.dlab.ise.shibaura-it.ac.jp/members.html",
"1. Akiho Okada, Midori Sugaya, 'Behavioral Design and Human-Robot Communication Considering with Activeness'.<br/>2. Yuhei Ikeda,Yoshiko Okada,  Midori Sugaya, 'How to Estimate Emotion? Method to Use Biological and Symbolic Information'<br/>3. Atsushi Hoshina, Yoshiko Okada, Midori Sugaya, 'Haptic Virtual Approach: Biological Effect on Touching and Viewing'<br><br><a href=\"http://2016.hci.international/\">http://2016.hci.international/</a>",
"会議名：「ロボット向け情報技術・設計技術に関する情報交換会」<br/>目的　：ロボット開発における情報技術・設計技術の重要性が増している。本会議においては、ロボット向けソフトウェアへの要求分析やクラウド活用における芝浦工大の取り組み、ロボットにおける消費エネルギー最適化技術に関する京都大学の取り組み、ロボット向けシステム設計技術に関する宇都宮大学の取り組む、を相互に紹介し、技術交流と意見交換を実施する。日時　：2015/12/15(火) 15:00～18:00<br/>場所　：芝浦工業大学豊洲キャンパス 研究棟14A32号室<br/>　　　　〒135-8548　江東区豊洲3-7-5<br/><br/>プログラム（予定）：<br/>15:00-15:30 「ROS準拠FPGAコンポーネント技術＆仕様案」<br/>（宇都宮大学M1・山科, B4・木村、大川）<br/>15:30-16:00 「（仮）SLAMのFPGA処理によるエネルギー効率向上」<br/>（京都大学B4・森、高瀬）<br/>16:00-16:30 「FPGA・クラウド連携による効率的なSLAM処理方式」<br/>（宇都宮大学B4・松本、大川）<br/>16:30-17:10 「（仮）ROSロボットクラウドの要求分析と構成検討」<br/>16:30-17:02 （芝浦工大・各約8分）<br/>　「 IXM : ロボットシステム向け通信ミドルウエアの提案（M2 住谷）」<br/>　「分散ロボットシステムサーバのための応答性向上手法（M1 中山）」<br/>　「複数台の分散移動ロボットの動作特性に基づく電力量の削減(B4 清水)」<br/>　「ロボットソフトウエアにおけるコンテキスト指向プログラミング適用（B4 小野）」<br/>   「ロボットクラウドの要求分析と構成検討」（菅谷）」<br/>17:10-18:00 総合討論「ロボット向け情報技術・設計技術の今後の戦略」<br/><br/>-参加者（予定）：<br/>　　　　芝浦工業大学工学部 准教授 菅谷みどり、他学生数名<br/>　　　　京都大学大学院情報学研究科 助教 高瀬英希、他学生数名<br/>　　　　宇都宮大学大学院情報工学科　助教 大川猛、他学生数名<br/>",
"Satoru Nakayama, Miyuki Nakano, Midori Sugaya<br/>Responsive Server For Distributed Care Robot System<br/><br/>Masaaki Yanagid, Miyuki Nakano, Midori Sugaya<br/>Node Buffer Control Mechanism for Distributed Robotics Systems<br/>",
"戸辺研究室URL：<a html=\"http://rcl.it.aoyama.ac.jp/?page_id=31\">http://rcl.it.aoyama.ac.jp/?page_id=31</a><br/>藤田研究室URL：<a href=\"http://sci-journalism.ws.hosei.ac.jp/wp\">http://sci-journalism.ws.hosei.ac.jp/wp/</a>",
"<DL>http://www.nikkan.co.jp/eve/irex/",
"10/13, 10/20 5限，503教室にてプレゼミを実施しました．<br/>参加して下さった3年生のみなさん，ありがとうございました！<br/><br/>下記に菅谷研プレゼミ課題の掲載を致します．<br/><br/>・課題<br/>「研究紹介を聞いて，自分が興味をもった研究とその理由（複数可能），やってみたいことをA4のレポートにまとめる」<br/>・提出期限<br/>　10月27日（火）<br/>　研究室前のレポート箱に提出",
"Feel as Agent: Immersive Dollhouse Enhances Sociality of Children with Developmental Disorders, Midori Sugaya, Yoshiko Okada, Hirotaka Osawa, Irini GIANNOPULU, HAI 2015: The 3rd International Conference on Human-Agent Interaction, 2015. Korea.",
"<DL>http://www.ahi-soc.info/poster.html",
"<DL>http://kes2015.kesinternational.org/",
"<DL>https://www.ht.sfc.keio.ac.jp/iwsc15/program/",
"2015, 09, 大倉研, 木村研とプレ中間を実施しました．",
"2014年度URL：<a href=\"https://www.ipsj.or.jp/event/s-seminar/2014/Exciting_Coding/\">https://www.ipsj.or.jp/event/s-seminar/2014/Exciting_Coding/</a>",
"本校の学部３年生による提案デバイスのプロトタイプ作成を行いました．<br/>製作物：<a href=\"https://youtu.be/OlQE4xQJ49I\">https://youtu.be/OlQE4xQJ49I</a>",
"<DL>http://hint.cse.oka-pu.ac.jp/roman2015_ws.html",
"8/30-31 研究室合宿で熱海に行ってきます！",
"<DL>http://2015.hci.international/friday#6",
"藤波研：<a href=\"http://www.tuat.ac.jp/~fujinami/lab/Top_page.html\">http://www.tuat.ac.jp/~fujinami/lab/Top_page.html</a>",
"DICOMO2015シンポジウム(<a href=\"http://dicomo.org/\" target=\"_blank\">公式HP</a>)<br/>日時:平成27年7月8日(水)～10日(金)<br/>会場:ホテル安比グランド本館＆タワー館<br/>　 　〒028-7396　岩手県八幡平市安比高原<br/><br/>セッション 7B スマートホーム<br/>日時: 2015年7月10日(金) 9:30 - 9:50)<br/>部屋: 竜ヶ森2<br/>題名:7B-4 Active Sensing ：移動ロボットによる見守りシステムの実現<br/>発表者:住谷拓馬<br/>著者:住谷 拓馬 (芝浦工業大学工学部情報工学科), 中野 美由紀 (芝浦工業大学教育イノベーション推進センター), 小野 建也, 浅沼 亮平, 菅谷 みどり (芝浦工業大学工学部情報工学科)<br/><br/>セッション 8D  認知・心理・感情<br/>日時: 2015年7月10日(金) 11:10 - 11:30<br/>部屋: 奥入瀬<br/>題名:ロボットハンドモーションによる感情伝達<br/>発表者:池田悠平<br/>著者:矢野 雄也, 池田 悠平, 岡田 明帆, 中野 美由紀, 菅谷 みどり (芝浦工大)",
"<DL>http://www.ieice.org/ken/program/index.php?tgs_regid=c234ff218868768c17e18fec406c3d89f8614dc45ab55b9a135a435c430e86cc&tgid=IEICE-CNR&lang=",
"<DL>/toyosuday_2015.html",
"豊洲Day<br/>日時:平成27年6月9日（火）<br/>会場:芝浦工業大学 豊洲キャンパス 研究棟14A32<br/><br/>研究棟14階のエレベータを出て右一番奥の研究室です．<br/>当日は本研究室の研究内容とデモを行いたいと思います．<br/>B4とM1,M2によるポスター発表，ロボットを使ったデモは，実際に見て触れることもできます！<br/>時間の関係で詳しいところまでは説明できませんが，菅谷研の特長やロボットに触れる楽しさを感じてくださると幸いです．<br/><br/>---*---message---*---<br/>ロボットと聞くと，pepperのような人型のものが真っ先に浮かびませんか？<br/>我々はiRobot createというロボットを使用し, 様々な研究に取り組んでいます．<br/>もちろん，研究内容によっては人型ロボットを使用している人もいます．<br/>プログラミングだけが情報ではありません！<br/>基盤を組み立てる楽しさ，ものをつくる楽しさ，研究室の若さ故の自由さがここにはあります！<br/>やりたいことが決まっている人も決まっていない人も,一度足を運んで見てください．<br/>研究室一同，心よりお待ちしております！<br/><br/>参照：<a href=\"/toyosuday.html\">2014/06/10 豊洲Dayの様子</a><br/>---------------------------***<br/>",
"<img src=\"images/enPIT_2015_2.jpg\" width=\"288px\" height=\"384px\" align=\"right\"><br/>enPIT スプリングスクール<br/>日時:平成27年5月9日（土）~10日（日）<br/>会場:東海大学高輪キャンパス，九州大学伊都キャンパス同時開催<br/><br/>9日と10日の2日間は会場にて講演、チームプロジェクトの課題の説明を受けました．<br/>11日（月）~16日（金）の間に製作を行い，17日（土）に発表を行いました．<br/><br/><img src=\"images/enPIT_2015.jpg\" width=\"340px\" height=\"240px\">    <img src=\"images/enPIT_2015_3.jpg\" width=\"340px\" height=\"240px\">",
"Miyuki YANAGI, Midori SUGAYA, Ryota HORIE(Shibaura Institute of Tenonology), How Kawaii Attributes are Composed in a Thing, Asian CHI Symposium, Japanese Culture and Kansei, 2015. Korea.<br/><br/><a href=\"http://user-engineering.net/SIGCHI2015/sub2.html\"Target=\"_blank\">詳細</a>",
"第46回研究会<br/>主催：情報処理学会ユビキタスコンピューティングシステム（UBI）研究会<br/>日時：平成27年5月11日（月）~12日（火）12:00~13:30<br/>会場:名古屋大学（東山キャンパス）　ベンチャービジネスラボラトリ　ベンチャーホール<br/>交通アクセス：<a href=\"http://www.vbl.nagoya-u.ac.jp/access.html\"Target=\"_blank\">http://www.vbl.nagoya-u.ac.jp/access.html</a> 参照<br/><br/>5月11日（月）一日目<br/>表彰式　13:00~13:30<br/>受賞者:渡辺 柚佳子<br/>タイトル：橙色の屋根のお家：コミュニケーションに障害を持つ児童向けのデジタル教材の提案と評価<br/><br/>5月12日（火）二日目<br/>セッション4 ヘルスケア 座長<br/>10:00~11:15(発表20分,質疑応答5分)<br/>発表者:菅谷 みどり 吉田 裕幸,渡辺柚佳子,中野 美由紀<br/>タイトル:自転車と歩行者の接近検知による事故防止の検討<br/><br/><a href=\"http://sigubi.ipsj.or.jp/seminar/\"Target=\"_blank\">詳細</a>",
	"第20回　人間情報学会<br/>日時：平成27年4月23日（木）12:00~13:30<br/>会場:東京大学　山上会館　2階　大会議質前<br/><br/>タイトル：ロボットモーションによる感情伝達の検討<br/>　　池田悠平,矢野雄也,渡辺 柚佳子,岡田佳子,菅谷みどり<br/><br/>タイトル：デジタルセラピーにおける評価手法の検討<br/>　　保科篤志,渡辺柚佳子,菅谷みどり",	
"<DL>http://www.shibaura-it.ac.jp/education/action/aword.html",
	"第45回ユビキタス研究会<br/>日時: 2015年3月2日(月) - 3(火)</br>会場: 芝浦工業大学（豊洲キャンパス）</br>&nbsp;&nbsp;&nbsp;&nbsp;〒135-8548東京都江東区豊洲3-7-5<br/>&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"http://www.shibaura-it.ac.jp/access/toyosu.html\">交通アクセス</a><br/><br/>テーマ:<br/>&nbsp;&nbsp;&nbsp;&nbsp;モバイルアドホックネットワーク, モバイル時代を支える次世代無線技術,<br/>&nbsp;&nbsp;&nbsp;&nbsp;フィールドセンシング, モバイルアプリケーション, ユビキタスサービス,<br/>&nbsp;&nbsp;&nbsp;&nbsp;ユビキタスシステム, 一般<br/><br/>発表者: 渡辺 柚佳子<br/>タイトル: 橙色の屋根のお家：コミュニケーションに障害を持つ児童向けのデジタル教材の提案と評価",
	"日時: 平成27年3月6日（金） - 7日（土）<br/>会場: 奄美市社会福祉協議会　会議室（2F・4F）<br/>&nbsp;&nbsp;&nbsp;&nbsp;〒894-0036 鹿児島県奄美市名瀬長浜町５-６<br/>会場連絡先　TEL 0997-52-7601　http://amamishakyo.org/<br/>空港からリムジンバス利用で70分（ウエストコート前下車）",
//	"",
	"<DL>https://www.gakkai-web.net/gakkai/ipsj/temporary_program/program77.html",
	"<DL>http://www.dlab.ise.shibaura-it.ac.jp/members.html",
	"Digital Play Therapy for Children with Learning Disabilities, <br />Yukako Watanabe, Yoshiko Okada, Hirotaka Osawa and Midori Sugaya<br /><br /><a href=\"http://2015.hci.international/\">HCI International 2015</a>",
	"国際学会 HAI2014 (Human Agent Interaction) にて，<br />渡辺さん，樫村君のポスター発表<br />(Digital Play Therapy for Children with Learning Disabilities, Yukako Watanabe, Yoshiko Okada, Hirotaka Osawa and Midori Sugaya)が<br />BEST POSTER AWARD First Place を受賞しました。<br /><center><a href=\"http://hai-conference.net/hai2014/\">HAI2014のページ</a><br /><img src=\"images/HAI2014_0.JPG\" width=\"240px\" height=\"320px\">&nbsp;<img src=\"images/HAI2014_1.JPG\" width=\"240px\" height=\"320px\"><br /><img src=\"images/HAI2014_2.JPG\" width=\"240px\" height=\"320px\">&nbsp;<img src=\"images/HAI2014_4.JPG\" width=\"240px\" height=\"320px\"></center>",
	"情報処理学会ユビキタスコンピューティングシステム(UBI)研究会 第43回UBI研究発表会にて，<br />渡辺 柚佳子さんの発表<br />「橙色の屋根のお家：コミュニケーションに障害を持つ児童向けのデジタル教材」が<br />学生奨励賞を受賞しました。<br /><center><a href=\"http://www.ipsj.or.jp/kenkyukai/event/ubi43.html\">UBIのページ</a></center>",
	"日付:&nbsp;[第1回]10/21(火)、[第2回]10/28(火)<br />教室:&nbsp;<font color=\"#ff0000\">506</font>教室<br />時間:&nbsp;5限(16:20-17:50)<br /><br />研究紹介や先輩方のおもしろい？話が聞けますので<br />どうぞいらしてください！（￣ー￣）ノ<br /><br /><b>プレゼミ課題について</b><ul><li>研究紹介を聞いて、自分が興味をもった研究とその理由（複数可能）、やってみたいことをA4のレポートにまとめて提出</li></ul><b>提出期限</b><ul><li>10月31日（金）&nbsp;->&nbsp;<font color=\"ff0000\">11月7日（金）</font>(芝祭期間により変更しました。)</li><li>研究室前のレポート箱に提出</li></ul>各発表者の発表資料<br />[10/21]<ul><li><a href=\"prezemi/2014_prezemi_watanabe.pdf\">渡辺_橙色の屋根のお家&nbsp;コミュニケーションに障害を持つ児童向けのデジタル教材</a></li><li><a href=\"prezemi/2014_prezemi_kashimura.pdf\">樫村_Theatre&nbsp;Fourze&nbsp;舞台演出手法を取り入れたCGとセンサー連携のための開発環境の提案</a></li><li><a href=\"prezemi/2014_prezemi_yoshida.pdf\">吉田_自転車の接近を警告する歩行者支援システムの提案</a></li><li><a href=\"prezemi/2014_prezemi_yano.pdf\">矢野_ロボットハンドモーションを実現するライブラリの提案</a></li><li><a href=\"prezemi/2014_prezemi_furukawa.pdf\">古川_ルールベースアドバイスによる人狼ゲームサポートシステムの提案</a></li><ul>[10/28]<ul><li><a href=\"prezemi/2014_prezemi_miyairi.pdf\">宮入_スマートフォンとロボットを利用した治療促進インターフェースの提案</a></li><li><a href=\"prezemi/2014_prezemi_sumiya.pdf\">住谷_リアルタイム処理と省電力を支援するロボットミドルウェア</a></li><li><!--<a href=\"prezemi/2014_prezemi_asanuma.pdf\">-->浅沼_(準備中)<!--</a>--></li><li><a href=\"prezemi/2014_prezemi_nagamine.pdf\">長峰_見守りロボットの省電力化の検討</a></li><li><a href=\"prezemi/2014_prezemi_yanagida.pdf\">柳田_ロボットのクラウド化におけるリアルタイム処理の検討</a></li><li><a href=\"prezemi/2014_prezemi_azuma.pdf\">東_空撮ロボットのバッテリ使用量にもとづく実行時間推定手法の提案</a></li><li><a href=\"prezemi/2014_prezemi_nakayama.pdf\">中山_教育向けネットワークロボットプラットフォームの提案</a></li><li><!--<a href=\"prezemi/2014_prezemi_hiranuma.pdf\">-->平沼_(準備中)<!--</a>--></li></ul>",
	"10/10(金)<br />教室:&nbsp;401教室(交流棟4階奥)<br />時間13:00~&nbsp;(菅谷研究室は<font color=\"#ff0000\">15:40~18:14</font>)<br /><br />教室内で発表を聴くことができますので、<br />お時間がある方はどうぞいらしてください！",
	"<a href=\"http://swest.toppers.jp/SWEST16/program.html\">組込みシステム技術に関するサマーワークショップ</a><br />住谷拓馬，長峰貴矩がポスター発表しました．",
	"<DL>http://www.dlab.ise.shibaura-it.ac.jp/fabgirl/index.html",
	"<img src=\"images/ec2014_0.JPG\" width=\"320px\" height=\"240px\"><img src=\"images/ec2014_1.JPG\" width=\"320px\" height=\"240px\"><img src=\"images/ec2014_2.JPG\" width=\"320px\" height=\"240px\"><br /><a href=\"http://ec2014.entcomp.org/program.php\">学会プログラム</a><br /><ul><li>橙色の屋根のお家： コミュニケーション向上に向けた訓練デバイス<br />渡辺 由佳子，河合 広至，樫村 健人，菅谷 みどり（芝浦工業大学）<br />河合君が発表＆デモをしました．</li><li>舞台演出手法を取り入れたMixed Reality アプリケーション開発環境<br />樫村 健人（芝浦工業大学），大澤 博隆（筑波大学），菅谷 みどり（芝浦工業大学）</li></ul>",
	"Yukako Watanabe, Yoshiko Okada, Hirotaka Osawa, Midori Sugaya<br /><a href=\"http://hai-conference.net/hai2014/program/\">Digital Play Therapy for Children with Learning Disabilities</a><br />",
	"",
	"",
	"<DL>http://ubiwww.ht.sfc.keio.ac.jp/seminar43/",
	"",
	"<DL>http://www.dlab.ise.shibaura-it.ac.jp/fabgirl/work.html",
	"<DL>http://www.dlab.ise.shibaura-it.ac.jp/fabgirl/",
	"<DL>http://www.dlab.ise.shibaura-it.ac.jp/toyosuday.html",
	"下記の研究デモを披露しました。<br /><ul><li>見守りシステム</li><li>ネットワークロボットに向けてのライブラリ設計</li><li>マルチコアの消費電力表示</li><li>クラウド</li><li>Raspberry Piを使ったデジタルカメラ</li><li>人狼ゲームサポートデバイス</li><li>Blended Reality Platform</li><li>Blended Reality Device (橙色のお屋根の家)</li><li>自転車の制動を警告する歩行者支援システム</li><li>スマートフォンとロボットとの連携</li></ul><br />たくさんの方々にお越しいただき、ありがとうございました！<br />豊洲Dayでの様子を<a href=\"toyosuday.html\">別ページ</a>で掲載しました。",
	"<ul><li>第184回ソフトウェア工学・第33回組込みシステム合同研究発表会</li><li>日時&nbsp;:&nbsp;平成26年5月19日（月）〜20日（火）</li><li>会場&nbsp;:&nbsp;株式会社日立製作所  日立研究所（勝田地区）</li></ul><br /><ul><li>タイトル&nbsp;:&nbsp;家庭用移動ロボットを用いた見守りシステムの実現</li><li>共著者&nbsp;:&nbsp;住谷拓馬, 菅谷みどり</li><li>発表者&nbsp;:&nbsp;住谷拓馬</li></ul>",
	"<ul><li>松田 暁,中村 広幸,菅谷 みどり, Luminous Sound Indicator: 光を用いた音源を察知するための注意喚起デバイス, 第157回ヒューマンコンピュータインタラクション研究会, 東京, 中野, 3月, 2014年.</li><li>菅谷 みどり, 新しいHCIデバイス開発のための実践演習, 第157回 ヒューマンコンピュータインタラクション研究会, 東京, 中野, 3月, 2014.</li></ul>",
	"<ul><li>木下智也，菅谷みどり, 移動体ロボットによる見守りの検討, 第76回情報処理学会全国大会, 東京, 3月, 2014年.</li><li>住谷拓馬，菅谷みどり, マルチパーパスロボットを実現する機能統合システムの提案, 第76回情報処理学会全国大会, 東京,  3月, 2014年. <b>学生奨励賞受賞</b>.</li><li>鈴木達也，菅谷みどり, 転倒検知による見守りシステムの実現, 第76回情報処理学会全国大会, 東京, 3月, 2014年.</li><li>河合広至，菅谷みどり, Arduinoを用いた自律同期通信システムの提案, 第76回情報処理学会全国大会, 東京, 3月, 2014年.</li><li>長谷川弘享，菅谷みどり, 異常プロセスの検知と隔離によるセルフヒーリングシステムの提案, 第76回情報処理学会全国大会, 東京, 3月, 2014年.</li></ul>",
	"<ul><li>渡辺 柚佳子，樫村 健人，吉田 裕幸，矢野 雄也，住谷 拓馬，河合 広至，菅谷 みどり, センサー入力とCGの連携を体験する演習教材, 第18回一般社団法人情報処理学会シンポジウム, 2月27-3月1日, 2014年.</li><li>菅谷 みどり, Arduinoとセンサーを教材としたHCIデバイス製作演習の実践, 第18回一般社団法人情報処理学会シンポジウム, 2月27-3月1日, 2014年.</li></ul>",
	"<ul><li>長谷川 弘享, 菅谷 みどり, 異常プロセスの検知と隔離によるセルフヒーリングシステムの提案, 第25回コンピュータシステムシンポジウム(ComSys 2013), 12月, 豊洲, 東京, 2013年.</li></ul>",
	"<ul><li>住谷拓馬，河合広至，菅谷みどり, 移動ロボット上でのサービス統合システムの提案, 組込みシステムシンポジウム2013, 国立オリンピック青少年センター, 10月, 2013年.</li></ul>"
];
